lang: cava_nlp
components:
  weight_value:
    factory: rule_engine
    config:
      token_label: weight
      value_label: weight_value
      entity_label: WEIGHT
      token_patterns: ${patterns.weight.token}
      value_patterns: ${patterns.weight.value}
      norm_patterns: ${patterns.weight.norm}
      exclusions: ${patterns.weight.exclusions}
      merge_ents: true